### ISSUE TITLE
two fatal errors during test

### ISSUE THREAD

**Issue by braindevices** [pydata/patsy#69] opened 2015-05-31 22:40 UTC
system versions:

    Python 2.7.6
    >>> patsy.__version__
    '0.3.0'
    >>> numpy.__version__
    '1.8.1'
    >>> pandas.__version__
    '0.16.1'

test results:

    .............py276/lib/python2.7/site-packages/pandas/core/categorical.py:472: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
    warn("Accessing 'levels' is deprecated, use 'categories'", FutureWarning)
    py276/lib/python2.7/site-packages/pandas/core/categorical.py:420: FutureWarning: 'labels' is deprecated. Use 'codes' instead
    warnings.warn("'labels' is deprecated. Use 'codes' instead", FutureWarning)
    ...FF.................
    ======================================================================
    FAIL: patsy.test_highlevel.test_formula_likes
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "py276/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    File "py276/lib/python2.7/site-packages/patsy/test_highlevel.py", line 202, in test_formula_likes
        [[1], [2], [3]], ["x"])
    File "py276/lib/python2.7/site-packages/patsy/test_highlevel.py", line 104, in t
        expected_lhs_values, expected_lhs_names)
    File "py276/lib/python2.7/site-packages/patsy/test_highlevel.py", line 32, in check_result
        assert rhs.design_info.column_names == expected_rhs_names
    AssertionError

    ======================================================================
    FAIL: patsy.test_highlevel.test_return_pandas
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "py276/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    File "py276/lib/python2.7/site-packages/patsy/test_highlevel.py", line 348, in test_return_pandas
        assert np.array_equal(df4.columns, ["AA"])
    AssertionError

    ----------------------------------------------------------------------
    Ran 35 tests in 65.391s

    FAILED (failures=2)

**Comment by yarikoptic** [comment] 2015-07-22 15:39
Exactly the same thing was reported in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792066
and now I have replicated with fresh release 0.4.0 ... didn't check in detail yet

**Comment by njsmith** [comment] 2015-07-22 15:48
Odd, 0.4.0 definitely should have fixed this...! Are you sure you you're
seeing is the same?

**Comment by yarikoptic** [comment] 2015-07-22 21:01
sorry for the noise -- indeed it was testing systemwide installed one, because somehow easy_install managed to inject its nasty /usr/local/lib/python2.7/dist-packages/easy-install.pth ... I will test with 0.4.0 now ;)

**Comment by njsmith** [comment] 2015-07-22 21:02
Well, there's an easy *cough* solution to easy_install woes...

**Comment by braindevices** [comment] 2015-07-22 21:23
@yarikoptic @njsmith This problem had been solved by installing git master version long time ago. So I guess it should not have problem with 0.4.0.

**Comment by yarikoptic** [comment] 2015-07-22 21:26
I can confirm now that fixed with 0.4.0  and could be closed. thanks! ;)

**Comment by njsmith** [comment] 2015-07-22 21:27
Great, thanks!

**Closed by njsmith** 2015-07-22 21:27 UTC
