### ISSUE TITLE
[question] How to get full-ranked categorical data?

### ISSUE THREAD

**Issue by shivamkalra** [pydata/patsy#94] opened 2016-10-05 15:05 UTC
My data consists of four columns, lets say `a, b, c, d`. Where `a` and `b` is categorical data with 3 and 5 categories each. My formula is `d = C(a) + C(b) + c` and even tried `d = 0 + C(a) + C(b) + c` but none of them is giving me full-ranked data so that I've all 3 and 5 categories in my final input data. Is there way to force patsy to give me full-ranked data?

**Comment by njsmith** [comment] 2016-10-05 15:16
There isn't any way baked into patsy currently.

You could do it "by hand" by defining a custom constrast coding scheme -- see https://patsy.readthedocs.io/en/latest/categorical-coding.html

Something like `C(a, np.eye(3))` for a variable with 3 levels would get you started. It wouldn't much more work to define a proper coding class that automatically handles different numbers of levels and gives you nicer column names -- search for `MyTreat` in the docs linked above for an example. And the next step beyond that would be to write up some tests and submit a pull request adding your coding class to patsy itself :-)

(Closing as a duplicate of #60.)

**Closed by njsmith** 2016-10-05 15:16 UTC
